import React from 'react';
import { CommonProps, Size } from '../generic';

export type SvgProps = { size?: Size } & CommonProps<SVGElement>;
export type SvgElemType = React.ForwardRefExoticComponent<SvgProps>;

export const IconInfo: SvgElemType;
export const IconWarning: SvgElemType;
export const IconError: SvgElemType;
export const IconOk: SvgElemType;
export const IconClear: SvgElemType;
export const IconArrowLeft: SvgElemType;
export const IconArrowRight: SvgElemType;
export const IconArrowDown: SvgElemType;
export const IconStar: SvgElemType;
export const IconStarBorder: SvgElemType;
export const IconStarHalf: SvgElemType;
export const IconChecked: SvgElemType;
export const IconUnChecked: SvgElemType;
export const IconRadioUnChecked: SvgElemType;
export const IconRadioChecked: SvgElemType;
export const IconList: SvgElemType;
export const IconSearch: SvgElemType;
export const IconClear2: SvgElemType;
export const IconHome: SvgElemType;
export const IconCalendar: SvgElemType;
export const IconChecked2: SvgElemType;
export const IconTime: SvgElemType;
export const IconNoData: SvgElemType;
export const IconQuestion: SvgElemType;
export const IconAccount: SvgElemType;
export const IconLock: SvgElemType;
export const IconEdit: SvgElemType;
export const IconPwdVisible: SvgElemType;
export const IconPwdInvisible: SvgElemType;
export const IconArrowDropDown: SvgElemType;
export const IconArrowRightBlack: SvgElemType;
export const IconArrowUp: SvgElemType;
export const IconCheckedIndeterminate: SvgElemType;
export const IconWarning2: SvgElemType;
export const IconLeftDoubleArrows: SvgElemType;
export const IconFilter: SvgElemType;
export const IconMore: SvgElemType;
export const IconRightDoubleArrows: SvgElemType;
